version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PACK_SIZES=250,500,1000,2000,5000
    volumes:
      - ./web:/app/web  # Mount web directory for development
    restart: unless-stopped

  # Optional: Add nginx for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    profiles:
      - production 